"""
Author: Mae Horak for masters thesis - Synesthetic Composition 2023

Description: What is synesthetic composition? It's an application I am
developing that uses imagery generated by machine learning that reacts
to live audio to combine the sense of hearing and sight.

This program takes input from a midi keyboard or live audio through a microphone
Then uses it to graph x and y coordinates that represent the "mood" of the music

https://github.com/mkh7878/synesthetic_composition

"""

from sound_inputs.midi_input import MidiInput
import threading
from video_output.color_window import SynestheticApp
from sound_inputs.mood_analysis import KeyAnaylsis

def main():
    # event = threading.Event()

    # Create an instance of MidiInput class
    midi_input = MidiInput()
    midi_input.find_midi_device()

    # Start a thread for the music_music method
    music_thread = threading.Thread(target=midi_input.music_music)
    music_thread.start()

#    analyse =

if __name__ == "__main__":
    main()
    SynestheticApp().run()

